# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e05a16aa6b7bf237c3554eea46a2ae57cd05f07245cc33e8b38b1bb83e6f909be30c13e6ffa49f9bd023abb7267222ab4b8f33f021772f003dbef45d27de2f

test:
  secret_key_base: c0cbabaac59135a64f5c1467a2f7e2bfee90f8877b8094c74198fdfb3fcad2bc2d589208f8f6147b8fef29d64eb95e1cd0c5860464805fdb3b54a27d63753166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
